apiVersion: v2
name: pagopa-remora-engine
description: REMORA Engine for PagoPA
type: application
version: 0.4.0
appVersion: v0.0.2
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
