microservice-chart: &microservice-chart
  namespace: "mock"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/andrea-deri/remora-engine
    tag: "v0.0.1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /r/ping
      port: 8080
      httpHeaders:
      - name: Content-Type
        value: application/json
    initialDelaySeconds: 30
    failureThreshold: 5
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /r/ping
      port: 8080
      httpHeaders:
      - name: Content-Type
        value: application/json
    initialDelaySeconds: 30
    failureThreshold: 5
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress: &ingress
    create: true
    host: "weudev.mock.internal.dev.platform.pagopa.it"
    path: /remora-engine/(.*)
    servicePort: 8080
  serviceAccount:
    name: "mock-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig: &envConfig
    DISPATCHER_MAX_ACCEPTED_REQUESTS: '128'
    DISPATCHER_MAX_CONCURRENT_REQUESTS: '64'
    DISPATCHER_CAN_CACHE_CONTENT: 'false'
    DISPATCHER_SPECIAL_ENDPOINT_PREFIX: 'r'
    HARBOR_DISPATCHER_LOGGING_LEVEL: 'trace'
    HARBOR_PROXY_LOGGING_LEVEL: 'trace'
    PROXY_EXPOSED_PORT: '8080'
    PROXY_PATH_PREFIX: '/'
    PROXY_REQUEST_TIMEOUT: '10'
    REGISTRY_API_TYPE: 'embedded'
    REGISTRY_LOAD_ALL_PROFILES_AT_STARTUP: 'true'
    REGISTRY_TYPE: 'mongo'
    TIDAL_MINNOW_PROFILES_UPDATE_POLLING_SECONDS: '60'
  envSecret: &envSecret
    REGISTRY_CONNECTION_STRING: 'db-mocker-uri'
  keyvault:
    name: "pagopa-d-mock-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - "user"
  canaryDelivery:
    create: false
    deployment:
      create: false
