name: Deploy on AKS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
      version:
        required: true
        type: string
        description: Select the version (as vMAJOR.MINOR.PATCH)

env:
  APP_NAME: pagoparemoraengine


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: [ self-hosted-job, "${{ inputs.environment }}" ]
    name: Deploy on AKS
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.CD_CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Helm Bump
        if: ${{ inputs.semver != 'skip' }}
        uses: pagopa/github-actions-template/helm-bump@main
        with:
          version: ${{ inputs.version }}
          beta: false

      - name: Push New Version
        if: ${{ inputs.semver != 'skip' }}
        shell: bash
        run: |
          echo "${{ steps.semver.outputs.version }}"
          git ls-files . | grep 'helm'  | xargs git add
          git config --global user.email "pagopa-platform-shared-github-bot@pagopa.it"
          git config --global user.name "pagopa-platform-shared-bot"
          if [ "${{ inputs.skip_ci }}" = "true" ]; then
              git commit -m "Bump to version ${{ inputs.version }} [skip ci]" || exit 0
            else
              git commit -m "Bump to version ${{ inputs.version }}" || exit 0
          fi
          git push origin ${{ github.ref_name}}

      - name: Deploy
        uses: pagopa/github-actions-template/aks-deploy@main
        with:
          branch: ${{ inputs.branch }}
          client_id: ${{ secrets.CD_CLIENT_ID }}
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          env: ${{ inputs.environment }}
          namespace: ${{ vars.NAMESPACE }}
          cluster_name: ${{ vars.CLUSTER_NAME }}
          resource_group: ${{ vars.CLUSTER_RESOURCE_GROUP }}
          app_name: ${{ env.APP_NAME }}
          helm_upgrade_options: '--debug 
            --set microservice-chart.azure.workloadIdentityClientId=${{ vars.WORKLOAD_IDENTITY_ID }} 
            --set microservice-chart.image.tag=${{ inputs.version }}'
          timeout: '5m0s'
